### ISSUE TITLE
Sweep: Make cmatrix compatible with M5Stack CardPuter

### ISSUE THREAD

**Issue by vs4vijay** [vs4vijay/cmatrix#4]
### Details
Sweep: Make cmatrix compatible with M5Stack CardPuter

and use following Github Actions CI to generate firmware binary for flashing:

```
      - name: Build using esp-idf
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4.6
          target: esp32s3
```

<details open>
<summary>Checklist</summary>

- [X] Create `esp32/main.c` ✓ https://github.com/vs4vijay/cmatrix/commit/5352921e33a27ec18555957379e6defde17b062f [Edit](https://github.com/vs4vijay/cmatrix/edit/sweep/make_cmatrix_compatible_with_m5stack_car/esp32/main.c)
- [X] Running GitHub Actions for `esp32/main.c` ✓  [Edit](https://github.com/vs4vijay/cmatrix/edit/sweep/make_cmatrix_compatible_with_m5stack_car/esp32/main.c)
- [X] Create `esp32/CMakeLists.txt` ✓ https://github.com/vs4vijay/cmatrix/commit/c7cd4ca5a8ae827091fef414d355482e3d0086f5 [Edit](https://github.com/vs4vijay/cmatrix/edit/sweep/make_cmatrix_compatible_with_m5stack_car/esp32/CMakeLists.txt)
- [X] Running GitHub Actions for `esp32/CMakeLists.txt` ✓  [Edit](https://github.com/vs4vijay/cmatrix/edit/sweep/make_cmatrix_compatible_with_m5stack_car/esp32/CMakeLists.txt)
- [X] Modify `README.md` ✓ https://github.com/vs4vijay/cmatrix/commit/627d10a23eccd2bcec4ff98f6264ebc6b1d79356 [Edit](https://github.com/vs4vijay/cmatrix/edit/sweep/make_cmatrix_compatible_with_m5stack_car/README.md#L68-L92)
- [X] Running GitHub Actions for `README.md` ✓  [Edit](https://github.com/vs4vijay/cmatrix/edit/sweep/make_cmatrix_compatible_with_m5stack_car/README.md#L68-L92)
- [X] Create `.github/workflows/esp-idf-build.yml` ✓ https://github.com/vs4vijay/cmatrix/commit/b498ab5b3066b92b0e8f667f78b54f32de4358ba [Edit](https://github.com/vs4vijay/cmatrix/edit/sweep/make_cmatrix_compatible_with_m5stack_car/.github/workflows/esp-idf-build.yml)
- [X] Running GitHub Actions for `.github/workflows/esp-idf-build.yml` ✗  [Edit](https://github.com/vs4vijay/cmatrix/edit/sweep/make_cmatrix_compatible_with_m5stack_car/.github/workflows/esp-idf-build.yml)
</details>

**Comment by vs4vijay** [comment]
Use following steps to make Github Actions CI pipeline to generate the firmware binary:

```

      - name: Build using esp-idf
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4.6
          target: esp32s3
```
